keywords:
  - extreme heat
  - climate change AND heat
  - BC heat wave
  - heat dome
  - climate action AND heat
  - heat
  - heatwave
  - heat wave
  - climate AND heat
  - climate crisis AND heat
  - heat stroke
  - heat illness
  - heat rash
  - heat exhaustion
  - warming planet
  - urban heat island
  - heat stress
  - hot weather
  - hot day
  - hottest day
  - hot summer
  - hottest summer
  - hottest year