subreddits:
  - canada
  - CanadaPolitics
  - onguardforthee
  - canada_sub
  - newfoundland
  - Alberta
  - NovaScotia
  - Ontario
  - Quebec
  - Saskatchewan
  - PEI
  - NewBrunswickCanada
  - Manitoba
  - BritishColumbia
  - NWT
  - Nunavut
  - Yukon
  - Yellowknife
  - Whitehorse
  - StJohnsNL
  - Calgary
  - Edmonton
  - Halifax
  - toronto
  - ottawa
  - Montreal
  - quebeccity
  - Regina
  - saskatoon
  - fredericton
  - Moncton
  - Winnipeg
  - vancouver
  - VictoriaBC